# Generated by Django 4.0.6 on 2022-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolistmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
